#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ── Config ────────────────────────────────────────────────────────────────────

const REQUIRED_FIELDS = ['path', 'href', 'name', 'desc', 'icon', 'author', 'category'];

const CATEGORY_ACCENT = {
  'Prototypes':    'accent-purple',
  'Design System': 'accent-blue',
  'User Research': 'accent-green',
  'Strategy':      'accent-red',
};
const ACCENT_CYCLE = ['accent-purple', 'accent-blue', 'accent-green', 'accent-red'];

const AUTHOR_DOT = {
  'Izabela': 'var(--dot-iz)',
  'Tzu-Yi':  'var(--dot-tz)',
  'Monica':  'var(--dot-mo)',
};
const DOT_FALLBACK = '#6B7280';

// ── Helpers ───────────────────────────────────────────────────────────────────

function getGitDate(projectPath) {
  try {
    // %e = space-padded day (POSIX, works on macOS + Linux)
    const raw = execSync(
      `git log --format="%ad" --date=format:"%b %e" -- "${projectPath}/" 2>/dev/null | head -1`,
      { encoding: 'utf8' }
    ).trim();
    // collapse the space-padding: "Apr  3" → "Apr 3"
    return raw ? raw.replace(/\s+/, ' ') : '—';
  } catch {
    return '—';
  }
}

function dot(author)     { return AUTHOR_DOT[author] || DOT_FALLBACK; }
function initial(author) { return author.charAt(0).toUpperCase(); }
function accent(category, idx) {
  return CATEGORY_ACCENT[category] || ACCENT_CYCLE[idx % ACCENT_CYCLE.length];
}

// ── Load + validate ───────────────────────────────────────────────────────────

const jsonPath = path.resolve(__dirname, '../projects.json');
let data;
try {
  data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
} catch (e) {
  process.stderr.write(`Error reading projects.json: ${e.message}\n`);
  process.exit(1);
}

const projects = data.projects || [];
const errors = [];
projects.forEach((p, i) => {
  REQUIRED_FIELDS.forEach(field => {
    if (!p[field]) errors.push(`projects[${i}] ("${p.name || i}") missing required field: "${field}"`);
  });
});
if (errors.length) {
  errors.forEach(e => process.stderr.write(`Validation error: ${e}\n`));
  process.exit(1);
}

// ── Group by category (preserving JSON order) ─────────────────────────────────

const categoryOrder = [];
const categoryMap   = {};
for (const p of projects) {
  if (!categoryMap[p.category]) {
    categoryMap[p.category] = [];
    categoryOrder.push(p.category);
  }
  categoryMap[p.category].push({ ...p, date: getGitDate(p.path) });
}

// ── Collect unique authors (preserving JSON order) ────────────────────────────

const authors = [...new Set(projects.map(p => p.author))];

// ── Render ────────────────────────────────────────────────────────────────────

function renderChips() {
  return authors.map(a => `
      <button class="contrib-chip" data-filter="${a}" aria-pressed="false">
        <div class="contrib-dot" style="background:${dot(a)}">${initial(a)}</div>
        <span class="contrib-name">${a}</span>
      </button>`).join('');
}

function renderRow(p) {
  return `
        <a class="project-row" href="${p.href}" data-author="${p.author}">
          <div class="row-icon">${p.icon}</div>
          <div class="row-meta">
            <span class="row-name">${p.name}</span>
            <span class="row-desc">${p.desc}</span>
            <span class="row-updated">Updated ${p.date}</span>
          </div>
          <div class="row-right">
            <div class="row-author">
              <div class="author-dot-sm" style="background:${dot(p.author)}">${initial(p.author)}</div>
              <span class="author-name">${p.author}</span>
            </div>
            <span class="row-path">${p.path}/</span>
            <span class="row-arrow">↗</span>
          </div>
        </a>`;
}

function renderSection(category, idx) {
  const items = categoryMap[category];
  return `
    <!-- ${category} -->
    <div class="section-group ${accent(category, idx)}">
      <div class="section-label">
        <span class="section-tag">${category}</span>
        <div class="section-rule"></div>
        <span class="section-count">${items.length}</span>
      </div>
      <div class="project-list">
${items.map(renderRow).join('')}
      </div>
    </div>`;
}

const sections = categoryOrder.map(renderSection).join('\n');

// ── Output ────────────────────────────────────────────────────────────────────
// NOTE: CSS and JS template lives here. To update the visual design, edit this
// file — not index.html (which is auto-generated on every deploy).

const html = `<!-- AUTO-GENERATED by scripts/generate-index.js — do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Age Bold — Playground</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=DM+Serif+Display:ital@0;1&display=swap" rel="stylesheet" />
  <style>
    /* ── Bold design system tokens ── */
    :root {
      --font-ui:      'Inter', system-ui, sans-serif;
      --font-display: 'DM Serif Display', Georgia, serif;

      --navy:         #001d56;
      --white:        #ffffff;
      --gray-50:      #fafafa;
      --gray-100:     #f5f5f5;
      --gray-150:     #E5E7EB;
      --gray-200:     #e5e5e5;
      --gray-500:     #6B7280;
      --gray-900:     #171717;
      --gray-muted:   #a3a3a3;

      --purple-600:   #5200d4;
      --blue-600:     #2563eb;
      --green-600:    #16a34a;
      --red-600:      #DC2626;

      --dot-iz: #6333E8;
      --dot-tz: #16a34a;
      --dot-mo: #2563eb;
    }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: var(--font-ui);
      background: var(--gray-100);
      color: var(--gray-900);
      min-height: 100vh;
      -webkit-font-smoothing: antialiased;
    }

    /* ── Top bar ── */
    .topbar {
      background: var(--navy);
      height: 52px;
      display: flex;
      align-items: center;
      padding: 0 24px;
      justify-content: space-between;
      position: sticky;
      top: 0;
      z-index: 100;
      animation: fadeDown 0.35s ease both;
    }

    .wordmark {
      display: flex;
      align-items: baseline;
    }

    .wordmark-brand {
      font-family: var(--font-display);
      font-size: 19px;
      font-style: italic;
      color: var(--white);
      letter-spacing: -0.2px;
    }

    .wordmark-sep {
      font-size: 14px;
      color: rgba(255,255,255,0.22);
      margin: 0 9px;
      font-weight: 300;
    }

    .wordmark-sub {
      font-size: 12px;
      font-weight: 500;
      color: rgba(255,255,255,0.45);
      letter-spacing: 0.4px;
      text-transform: uppercase;
    }

    .contrib-row {
      display: flex;
      align-items: center;
      gap: 5px;
    }

    /* Filter chips */
    .contrib-chip {
      display: flex;
      align-items: center;
      gap: 5px;
      padding: 3px 8px 3px 3px;
      background: rgba(255,255,255,0.07);
      border: 1px solid rgba(255,255,255,0.09);
      border-radius: 100px;
      cursor: pointer;
      font-family: var(--font-ui);
      transition: background 0.15s, border-color 0.15s;
    }

    .contrib-chip:hover {
      background: rgba(255,255,255,0.13);
      border-color: rgba(255,255,255,0.2);
    }

    .contrib-chip.active {
      background: rgba(255,255,255,0.18);
      border-color: rgba(255,255,255,0.38);
    }

    .contrib-chip.active .contrib-name {
      color: rgba(255,255,255,0.92);
    }

    .contrib-dot {
      width: 22px; height: 22px;
      border-radius: 50%;
      display: flex; align-items: center; justify-content: center;
      font-size: 10px;
      font-weight: 700;
      color: white;
      flex-shrink: 0;
    }

    .contrib-name {
      font-size: 12px;
      font-weight: 500;
      color: rgba(255,255,255,0.6);
    }

    /* ── Main ── */
    main {
      max-width: 820px;
      margin: 0 auto;
      padding: 8px 20px 64px;
    }

    /* ── Section group ── */
    .section-group {
      margin-top: 24px;
      animation: fadeUp 0.4s ease both;
    }
    .section-group:nth-child(1) { animation-delay: 0.06s; }
    .section-group:nth-child(2) { animation-delay: 0.13s; }
    .section-group:nth-child(3) { animation-delay: 0.20s; }
    .section-group:nth-child(4) { animation-delay: 0.27s; }

    .section-label {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 4px;
      padding: 0 2px;
    }

    .section-tag {
      font-size: 10px;
      font-weight: 700;
      letter-spacing: 0.9px;
      text-transform: uppercase;
      padding: 3px 8px;
      border-radius: 4px;
      flex-shrink: 0;
    }

    .section-rule {
      flex: 1;
      height: 1px;
      background: var(--gray-200);
    }

    .section-count {
      font-size: 11px;
      font-weight: 500;
      color: var(--gray-muted);
      flex-shrink: 0;
    }

    /* Section accent theming */
    .accent-purple .section-tag { background: #f0ebff; color: var(--purple-600); }
    .accent-blue   .section-tag { background: #ebf0ff; color: var(--blue-600); }
    .accent-green  .section-tag { background: #dcfce7; color: var(--green-600); }
    .accent-red    .section-tag { background: #fef2f2; color: var(--red-600); }

    /* ── Project rows ── */
    .project-list {
      display: flex;
      flex-direction: column;
      gap: 2px;
    }

    .project-row {
      display: grid;
      grid-template-columns: 34px 1fr auto;
      align-items: center;
      column-gap: 12px;
      padding: 9px 10px 9px 7px;
      border-radius: 10px;
      text-decoration: none;
      color: inherit;
      border-left: 3px solid transparent;
      transition: background 0.12s, border-color 0.12s, box-shadow 0.12s;
    }

    .project-row.row-hidden { display: none; }

    .accent-purple .project-row:hover { background: var(--white); border-left-color: var(--purple-600); box-shadow: 0 1px 8px rgba(82,0,212,0.07); }
    .accent-blue   .project-row:hover { background: var(--white); border-left-color: var(--blue-600);   box-shadow: 0 1px 8px rgba(37,99,235,0.07); }
    .accent-green  .project-row:hover { background: var(--white); border-left-color: var(--green-600);  box-shadow: 0 1px 8px rgba(22,163,74,0.07); }
    .accent-red    .project-row:hover { background: var(--white); border-left-color: var(--red-600);    box-shadow: 0 1px 8px rgba(220,38,38,0.07); }

    .row-icon {
      font-size: 16px;
      width: 34px; height: 34px;
      display: flex; align-items: center; justify-content: center;
      background: var(--white);
      border-radius: 8px;
      border: 1px solid var(--gray-150);
      flex-shrink: 0;
    }

    .row-meta {
      display: flex;
      flex-direction: column;
      gap: 2px;
      min-width: 0;
    }

    .row-name {
      font-size: 14px;
      font-weight: 600;
      color: var(--gray-900);
      line-height: 1.3;
    }

    .row-desc {
      font-size: 12px;
      color: var(--gray-500);
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    .row-updated {
      font-size: 11px;
      color: var(--gray-muted);
      font-weight: 400;
    }

    /* Fixed-column grid — pins author / path / arrow at identical X across all rows */
    .row-right {
      display: grid;
      grid-template-columns: 96px 130px 18px;
      align-items: center;
      column-gap: 10px;
      flex-shrink: 0;
    }

    .row-author {
      display: flex;
      align-items: center;
      gap: 5px;
      font-size: 12px;
      color: var(--gray-500);
      font-weight: 500;
      overflow: hidden;
    }

    .author-dot-sm {
      width: 18px; height: 18px;
      border-radius: 50%;
      display: flex; align-items: center; justify-content: center;
      font-size: 9px;
      font-weight: 700;
      color: white;
      flex-shrink: 0;
    }

    .row-path {
      font-size: 11px;
      color: var(--gray-muted);
      font-family: 'SF Mono', 'Fira Code', 'Menlo', monospace;
      letter-spacing: -0.2px;
      white-space: nowrap;
    }

    .row-arrow {
      font-size: 13px;
      color: var(--gray-200);
      transition: color 0.12s, transform 0.12s;
      justify-self: end;
    }

    .project-row:hover .row-arrow {
      color: var(--gray-500);
      transform: translate(2px, -2px);
    }

    /* ── Animations ── */
    @keyframes fadeDown {
      from { opacity: 0; transform: translateY(-8px); }
      to   { opacity: 1; transform: translateY(0); }
    }

    @keyframes fadeUp {
      from { opacity: 0; transform: translateY(8px); }
      to   { opacity: 1; transform: translateY(0); }
    }

    /* ── Responsive ── */
    @media (max-width: 600px) {
      .row-right { grid-template-columns: 96px 18px; }
      .row-path { display: none; }
      .contrib-name { display: none; }
      main { padding: 8px 12px 48px; }
      .topbar { padding: 0 16px; }
    }
  </style>
</head>
<body>

  <header class="topbar">
    <div class="wordmark">
      <span class="wordmark-brand">Age Bold</span>
      <span class="wordmark-sep">/</span>
      <span class="wordmark-sub">Playground</span>
    </div>
    <div class="contrib-row">${renderChips()}
    </div>
  </header>

  <main>
${sections}
  </main>

  <script>
    (function () {
      const active = new Set();

      document.querySelectorAll('.contrib-chip').forEach(chip => {
        chip.addEventListener('click', () => {
          const author = chip.dataset.filter;
          if (active.has(author)) {
            active.delete(author);
            chip.classList.remove('active');
            chip.setAttribute('aria-pressed', 'false');
          } else {
            active.add(author);
            chip.classList.add('active');
            chip.setAttribute('aria-pressed', 'true');
          }
          applyFilter();
        });
      });

      function applyFilter() {
        document.querySelectorAll('.section-group').forEach(group => {
          const rows = group.querySelectorAll('.project-row');
          let visible = 0;
          rows.forEach(row => {
            const show = active.size === 0 || active.has(row.dataset.author);
            row.classList.toggle('row-hidden', !show);
            if (show) visible++;
          });
          // Hide entire section when no rows match
          group.style.display = visible === 0 ? 'none' : '';
          // Update count
          const countEl = group.querySelector('.section-count');
          if (countEl) {
            countEl.textContent = active.size === 0 ? rows.length : visible + '/' + rows.length;
          }
        });
      }
    })();
  </script>

</body>
</html>
`;

process.stdout.write(html);
